version: "3"

services:
  spid-express-app:
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=dev
      - REDIS_URL=redis://redis
      - NODE_TLS_REJECT_UNAUTHORIZED=0
    expose:
      - "3000"
    ports:
      - "3000:3000"
    image: node:10.14.2-alpine
    working_dir: /usr/src/app
    command: ["yarn", "dev"]
    networks:
      - spid-express-app
    depends_on:
      - spid-saml-check

  spid-saml-check:
    image: italia/spid-saml-check
    ports:
      - "8080:8080"
    networks:
      - spid-express-app
    #volumes:
      #- "./docker/spid-saml-check-config/idp.json:/spid-saml-check/spid-validator/config/idp.json:ro"
      #- "./docker/spid-saml-check-config/idp_demo.json:/spid-saml-check/spid-validator/config/idp_demo.json:ro"
      #- "./docker/spid-saml-check-config/server.json:/spid-saml-check/spid-validator/config/server.json:ro"

  redis:
    image: wodby/redis:3.2-2.1.5
    environment:
      REDIS_TIMEOUT: 300
      REDIS_TCP_KEEPALIVE: 60
      REDIS_MAXMEMORY: 182m
    networks:
      - spid-express-app

# needed to make TSL work
networks:
  spid-express-app:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1450
