version: 2.1
jobs:
  spid_test:
    machine:
      image: ubuntu-2004:202104-01
    steps:
      - checkout

      - run: docker-compose up -d
      - run: sudo apt-get update && sudo apt-get install libxml2-dev libxmlsec1-dev libxmlsec1-openssl
      - run: pip3 install spid-sp-test
      - run: spid_sp_test --metadata-url http://localhost:3000/metadata --extra --debug ERROR --exit-zero

workflows:
  version: 2
  build:
    jobs:
      - spid_test
